// This generated by evm-cli, edit as necessary
package user

import (
	"github.com/go-chi/chi"

	"github.com/IlhamRobyana/user/internal/domain/user/service"
)

// UserHandler is the HTTP handler for User domain.
type UserHandler struct {
	UserService service.UserService
}

// ProvideUserHandler is the provider for this handler.
func ProvideUserHandler(svc service.UserService) UserHandler {
	return UserHandler{
		UserService: svc,
	}
}

// Router sets up the router for this domain.
func (h *UserHandler) Router(r chi.Router) {
	r.Route("/user", func(r chi.Router) {
		r.Group(func(r chi.Router) {
			r.Post("/", h.CreateUser)
			r.Get("/{id}", h.ResolveUserByID)
			r.Post("/login", h.LoginUser)
		})

	})
}
