// This generated by evm-cli, edit as necessary
package middleware

import (
	"github.com/IlhamRobyana/user/infras"
)

type Authentication struct {
	db *infras.MySQLConn
}

const (
	HeaderAuthorization = "Authorization"
)

func ProvideAuthentication(db *infras.MySQLConn) *Authentication {
	return &Authentication{
		db: db,
	}
}
