// This generated by evm-cli, edit as necessary
package model

import (
	"github.com/IlhamRobyana/user/shared/crypt"
	"github.com/google/uuid"
	"github.com/guregu/null/v5"

	"time"
)

const (
	Active   = "active"
	Inactive = "inactive"
)

type UserDBFieldNameType string

type userDBFieldName struct {
	Id        UserDBFieldNameType
	Email     UserDBFieldNameType
	Password  UserDBFieldNameType
	Fullname  UserDBFieldNameType
	Status    UserDBFieldNameType
	CreatedAt UserDBFieldNameType
	UpdatedAt UserDBFieldNameType
	DeletedAt UserDBFieldNameType
	CreatedBy UserDBFieldNameType
	UpdatedBy UserDBFieldNameType
	DeletedBy UserDBFieldNameType
}

var UserDBFieldName = userDBFieldName{
	Id:        "id",
	Email:     "email",
	Password:  "password",
	Fullname:  "fullname",
	Status:    "status",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
	CreatedBy: "created_by",
	UpdatedBy: "updated_by",
	DeletedBy: "deleted_by",
}

type User struct {
	Id        uuid.UUID   `db:"id"`
	Email     string      `db:"email"`
	Password  string      `db:"password"`
	Fullname  string      `db:"fullname"`
	Status    string      `db:"status"`
	CreatedAt time.Time   `db:"created_at"`
	UpdatedAt time.Time   `db:"updated_at"`
	DeletedAt null.Time   `db:"deleted_at"`
	CreatedBy string      `db:"created_by"`
	UpdatedBy string      `db:"updated_by"`
	DeletedBy null.String `db:"deleted_by"`
}

type UserList []*User

func (u User) ComparePassword(password string) (bool, error) {
	return crypt.CompareBcrypt(password, u.Password)
}
