// This generated by evm-cli, edit as necessary
package service

import (
	"github.com/IlhamRobyana/user/configs"
	"github.com/IlhamRobyana/user/infras"
	"github.com/IlhamRobyana/user/internal/domain/user/repository"
	"github.com/go-redis/redis/v8"
)

// UserService is the service interface for User entities.
type Service interface {
	UserService
}

// UserServiceImpl is the service implementation for User entities.
type UserServiceImpl struct {
	UserRepository repository.UserRepository
	cfg            *configs.Config
	cache          *redis.Client
}

// ProvideUserService is the provider for this service.
func ProvideUserService(repo repository.UserRepository, cfg *configs.Config) *UserServiceImpl {
	s := new(UserServiceImpl)
	s.UserRepository = repo
	s.cfg = cfg
	s.cache = infras.RedisNewClient(*cfg)
	return s
}
